bands = [
  {
    name: "The Who",
    members: ["John Entwistle", "Keith Moon", "Doug Sandom", "Kenney Jones"],
    logo: "640px-Who_-_1975.jpg",
    logoCredits:
      "By Jim Summaria - Contact us/Photo submission, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=5574716",
    bio: "The Who is English hard rock band formed in London, England in 1964. The members are Roger Daltrey (lead singer), Pete Townshend (guitarist), John Entwistle (bassist), and Keith Moon (drums). The genres they were associated with happened to be rock, soft rock, hard rock, and soul rock. They are best known for their live performances and hit songs Baba O'Riley, My Generation, and Won't Get Fooled Again. Some noted achievements were their rock operas, Tommy (album), Quadrophenia (album), and A Quick One, While He's Away (song). The Who still plays today, yet sadly, Keith Moon died in 1978 due to a accidental prescription pill overdose at the age of 32. His best friend, John Entwistle, soon followed.Entwistle died of a cocaine overdose in 2002 at the age of 57. Later, Townshend was accused of buying child pornography, but was proven innocent.Overall, in the end, The Who has contained some of the most influential talent in rock history with some of the most impressive instrumental skills, and manage to be a iconic mark in rock n roll to this day.",
    genre: "Hard Rock",
    day: "fri",
    scene: "Midgard",
    start: "04:00",
    end: "06:00",
  },
  {
    name: "Zboncak - Haag",
    members: ["Waylon Schoen", "Nola Gleason", "Rosendo Kuhic", "Sydney Cremin", "Hank Torphy"],
    genre: "Folk",
    logo: "https://placeimg.com/720/480/abstract?17289",
    bio: "Necessitatibus consectetur sed. Minus rerum ea nemo libero id quia quasi sunt. Dignissimos fuga reiciendis repudiandae modi. Consectetur ipsam dolores consequatur aut voluptate. Qui inventore facilis voluptatem qui fuga.\n \rNecessitatibus impedit debitis eaque necessitatibus omnis assumenda consequatur. Quia cum ipsam fugit. Nisi dolores perspiciatis.\n \rSapiente occaecati voluptatibus consectetur inventore eum qui harum quia officiis. Voluptas eum quia delectus repudiandae ex consequatur quisquam. Consequatur voluptatem officia dolores labore quas iusto. Consequuntur deleniti omnis illum placeat veniam quae.",
    day: "fri",
    scene: "Midgard",
    start: "16:00",
    end: "18:00",
  },
  {
    name: "West and Sons",
    members: ["Danial Ward", "Emery Gutkowski", "Izaiah Schowalter"],
    genre: "Folk",
    logo: "https://placeimg.com/720/480/nightlife?61846",
    bio: "Sunt delectus rem et voluptas est est. Dolorum debitis nisi provident dolor. Possimus facere ut recusandae eum excepturi tempora ex quia. Excepturi voluptatem hic quia amet consequuntur esse beatae. Aut quibusdam quibusdam est iure voluptas vitae numquam. Libero tempora veniam nobis possimus illo.\n \rRepellat qui amet non et et in cumque. Et asperiores et deserunt qui. Similique rerum labore praesentium. Laudantium quo commodi aut nihil possimus est et.\n \rQui cumque dignissimos quia laudantium ducimus sit neque enim. Perspiciatis fugiat veniam facilis id qui mollitia. Molestiae laborum nihil.",
    day: "fri",
    scene: "Midgard",
    start: "08:00",
    end: "10:00",
  },
  {
    name: "Price, Grant and Bechtelar",
    members: ["Timmothy Kuhn", "Ezekiel Veum"],
    genre: "Non Music",
    logo: "https://placeimg.com/720/480/nightlife?76715",
    bio: "Consequatur unde praesentium recusandae. Earum autem impedit ducimus. Vitae sed necessitatibus sint placeat suscipit sint quia. Quidem ex voluptatem eum sunt.\n \rEum quo unde culpa sunt. Commodi vero facilis. Et eum corrupti placeat. Laboriosam vitae hic odio aliquid. Ut est illum inventore optio.\n \rQui veritatis quos quam. Quaerat voluptatibus voluptatum autem expedita praesentium facere aut dolor veniam. Optio repellendus quo sit aut.",
    day: "fri",
    scene: "Vanaheim",
    start: "12:00",
    end: "14:00",
  },
  {
    name: "Barrows Group",
    members: ["Barney Nienow", "Jarod Renner", "Unique Russel"],
    genre: "Metal",
    logo: "https://placeimg.com/720/480/food?70562",
    bio: "Quae rerum est. Aut aut modi sapiente adipisci est aut dolorum. Ut et quod asperiores et. Quia consequatur magni animi consequatur omnis adipisci aut consequatur. Et ut fugit et aut rem consequatur optio qui occaecati. Voluptatem praesentium consequuntur a placeat nam qui illo.\n \rUt qui aliquam perferendis quibusdam alias porro similique et id. Deserunt repudiandae id. Voluptatem dolor adipisci ab minima ducimus. Eligendi doloribus sit qui et numquam rerum.\n \rHic eum minima cumque modi dolorem. Non ut eum maiores ut tempora non et harum. Omnis itaque magni ut qui reprehenderit. Aut magnam velit expedita doloremque at ut consequuntur. Veritatis eaque accusantium. Et delectus est est.",
    day: "fri",
    scene: "Jotunheim",
    start: "12:00",
    end: "14:00",
  },
  {
    name: "Ortiz Group",
    members: ["Anabel Deckow", "Frankie Hettinger", "Einar Breitenberg", "Kaitlin Dare"],
    genre: "Soul",
    logo: "https://placeimg.com/720/480/fashion?18788",
    bio: "Est voluptates tempora. Libero impedit non. Magni sunt voluptates iure dolorem. Eligendi cupiditate hic in aperiam ipsa similique voluptates et. Sit voluptate fugit ipsam odio fugit. Quos est asperiores ut id.\n \rIste repudiandae non rerum laborum. Molestias non vel sit ratione magni adipisci. Repellat enim sequi earum. Officia iste ut voluptatem. Et tenetur laborum maxime rem natus veniam explicabo. Porro dolores unde laborum rerum harum eos.\n \rArchitecto sapiente aut. Voluptatem quia architecto eaque ab aut repellat quisquam. Modi recusandae sed quod eveniet officiis.",
    day: "fri",
    scene: "Vanaheim",
    start: "00:00",
    end: "02:00",
  },
  {
    name: "Wehner Inc",
    members: ["Ahmed O'Hara", "Lonny Jakubowski", "Dannie Schumm", "Gwendolyn Sipes"],
    genre: "Folk",
    logo: "https://placeimg.com/720/480/animals?6747",
    bio: "Ut nemo quam voluptate rerum libero. Commodi consequuntur culpa officia eos architecto et. Id qui repellendus tempora in. Qui iusto dolorum. Culpa corporis eum fugit. Distinctio laboriosam debitis vel esse aliquid minus.\n \rSint et quis cupiditate deserunt exercitationem error accusamus neque. Rerum voluptatem iusto iusto fugit ab itaque aut impedit. Ut iure blanditiis est et quaerat sit. Numquam consequuntur doloremque culpa saepe quod aut cupiditate a.\n \rRem commodi ipsam commodi quia consequatur. Tenetur aspernatur quod nihil tempora atque velit id dolorum consequatur. Quo consectetur voluptate debitis repellendus qui temporibus exercitationem rerum tenetur.",
    day: "fri",
    scene: "Vanaheim",
    start: "20:00",
    end: "22:00",
  },
  {
    name: "West, Hauck and Langworth",
    members: ["Jewel Schulist", "Bella Wuckert"],
    genre: "Blues",
    logo: "https://placeimg.com/720/480/abstract?31954",
    bio: "Magnam perferendis aut doloribus. Nihil architecto iure occaecati. Ducimus deleniti sit itaque voluptas illo aliquam unde. Maxime placeat error mollitia enim earum. Inventore veritatis quasi velit.\n \rAut molestiae et dolores facere ipsum ut. Et laboriosam aliquid deserunt aliquid vero eius ut. Molestiae vitae fuga.\n \rIpsa sequi odit ducimus quia. Quisquam et sed dolor reiciendis sit. Beatae aliquam earum itaque eveniet aut dolores dolorum tempore. Asperiores error molestiae laboriosam repellat corrupti. Corrupti velit explicabo nesciunt quia.",
    day: "fri",
    scene: "Vanaheim",
    start: "08:00",
    end: "10:00",
  },
  {
    name: "Wiegand - Hickle",
    members: ["Adah McGlynn", "Orie Green", "Dora Weimann"],
    genre: "Blues",
    logo: "https://placeimg.com/720/480/nightlife?20219",
    bio: "Non et omnis reprehenderit. Vel ut est omnis. Repellat distinctio soluta velit quos voluptatum neque culpa dignissimos repellendus.\n \rEa quae quisquam. Fuga saepe aut illum consequatur. Fugit esse eligendi id excepturi qui sed aut eligendi.\n \rEt id natus quia. Exercitationem omnis neque quia eum blanditiis hic veritatis. Dolorum in nobis unde similique a possimus.",
    day: "fri",
    scene: "Midgard",
    start: "20:00",
    end: "22:00",
  },
  {
    name: "Auer - Towne",
    members: ["Samson Lynch", "Beau Mitchell"],
    genre: "Folk",
    logo: "https://placeimg.com/720/480/nightlife?10284",
    bio: "Ut provident impedit placeat eos accusamus dolorum magni aliquam illo. Consequatur corrupti nobis reiciendis nesciunt quia tempore distinctio. Qui eveniet iure ipsa et minus error. Libero distinctio occaecati at delectus nihil. Eligendi omnis voluptas. Reprehenderit perspiciatis nobis amet ducimus quasi doloremque aut magni qui.\n \rTempore dolores pariatur eos repellat adipisci et. Quia sint eos minima iure dolor labore aut. Eaque repellat quis. Et porro nihil iusto ipsam reiciendis quis autem. Quidem quibusdam ab exercitationem sunt quo itaque quo accusamus pariatur.\n \rUt sed qui magni libero maiores nostrum. Aliquid ipsum quas ut cum iste dignissimos tempore. Similique ut velit aspernatur ut nihil ut.",
    day: "fri",
    scene: "Vanaheim",
    start: "04:00",
    end: "06:00",
  },
  {
    name: "Schultz and Sons",
    members: ["Duncan Jacobi", "Earnestine Lubowitz"],
    genre: "Soul",
    logo: "https://placeimg.com/720/480/nightlife?59375",
    bio: "Vitae in eveniet. Sed voluptatum quas. Dolores veniam perspiciatis quisquam quia rerum est quia.\n \rQuos nam debitis enim ratione. Ab est et neque consequuntur ducimus voluptatem est eligendi. Corrupti et accusamus quos ut rerum.\n \rEnim illo et cupiditate commodi quia quaerat. Sint vel animi velit quis. Excepturi consequatur et deserunt alias magni voluptas. Quod amet maxime. Sequi ut dolor laboriosam molestias. Error aut est consequuntur hic reprehenderit labore quis ut nulla.",
    day: "fri",
    scene: "Jotunheim",
    start: "16:00",
    end: "18:00",
  },
  {
    name: "Leffler Group",
    members: ["Jairo D'Amore", "Allison Sauer"],
    genre: "Funk",
    logo: "https://placeimg.com/720/480/nature?41786",
    bio: "Sed molestiae aut. Inventore voluptate quam earum. Nemo rem voluptatem repellat quisquam adipisci tempora. Necessitatibus non aut iure blanditiis at.\n \rTotam officiis explicabo id et odio commodi ducimus. Dolorem architecto hic dignissimos magnam aperiam officia non aperiam doloribus. Ut consequuntur ea maiores magnam. Inventore quis repudiandae aut maiores et maiores sint hic qui. Porro sed nobis.\n \rVitae ut numquam aperiam deserunt veritatis quod harum. Aliquam et distinctio. Aut neque dolores sunt et consequatur consequatur vero porro. Delectus et qui dolore necessitatibus et est consequuntur distinctio. Rerum eum voluptatem velit. Vero iste omnis cum impedit recusandae et ex explicabo dolores.",
    day: "fri",
    scene: "Jotunheim",
    start: "08:00",
    end: "10:00",
  },
  {
    name: "Jacobs and Sons",
    members: ["Erwin Schroeder"],
    genre: "Funk",
    logo: "https://placeimg.com/720/480/nightlife?84920",
    bio: "Dolorem repudiandae repellendus odio itaque delectus. Magni consequuntur odit hic dolores porro nihil maxime mollitia. Reprehenderit laborum modi omnis sed tempore iste qui ut odio. Occaecati iusto voluptates in quia numquam. Magni unde ut et veniam.\n \rSit ex animi atque. Possimus non neque quisquam velit molestias necessitatibus explicabo provident sunt. Animi libero saepe iusto.\n \rEos deleniti sunt laboriosam eveniet necessitatibus voluptatem nulla reiciendis dolor. Commodi quia modi corporis fugit cumque quia. Sed voluptatem aut deserunt consequuntur. Itaque quo omnis et illo aut incidunt dolorem.",
    day: "fri",
    scene: "Midgard",
    start: "12:00",
    end: "14:00",
  },
  {
    name: "Bartell - Cummerata",
    members: ["Angus Hane", "Yasmine Kemmer"],
    genre: "Electronic",
    logo: "https://placeimg.com/720/480/fashion?86902",
    bio: "Doloribus quae laudantium. Nemo dolores est nihil aut corrupti sunt et. Qui iure in beatae labore nesciunt culpa sunt et exercitationem. Dolores ut maxime aliquid tempora consectetur porro expedita. Nihil explicabo iusto.\n \rRerum doloribus optio necessitatibus. Placeat unde minus nam commodi quam aspernatur. At quam cupiditate ut dignissimos. Quaerat assumenda et illo accusamus corporis. Placeat sunt aut enim dolorem neque doloribus cumque.\n \rVeritatis voluptas non nemo ea. Qui eius est natus ab commodi qui. Error quam est quia nobis. Ratione voluptas excepturi nesciunt aspernatur. Sint aut ipsa hic quibusdam voluptate ut nihil culpa. Consequuntur sint amet et labore nihil omnis.",
    day: "fri",
    scene: "Jotunheim",
    start: "00:00",
    end: "02:00",
  },
  {
    name: "Farrell, Ullrich and Ebert",
    members: ["Maritza Morar", "Elmore Heaney", "Alice Ernser"],
    genre: "Latin",
    logo: "https://placeimg.com/720/480/people?81672",
    bio: "Est iure quibusdam consequatur est blanditiis pariatur esse. Non quis voluptas aperiam. Sint ad accusantium non dolor et tempore amet sed. Ducimus perferendis id quod molestias quis fugiat dolorem minima. Animi itaque cum sed.\n \rAdipisci et porro vitae provident aut voluptatum iure consequatur molestiae. Sit ut quo eaque dolorem. Suscipit deleniti officia eos eos dolorem aut sit et. Autem quod dolores. Sint velit aut quasi cupiditate porro repellendus.\n \rRepellendus aperiam pariatur labore sed excepturi iste et asperiores. Cupiditate natus accusantium quas iure fuga consectetur. Natus minus aut autem.",
    day: "fri",
    scene: "Midgard",
    start: "00:00",
    end: "02:00",
  },
  {
    name: "Breitenberg, Marvin and Green",
    members: ["Amya Douglas", "Kurt Hettinger", "Enrique Macejkovic"],
    genre: "World",
    logo: "https://placeimg.com/720/480/animals?57288",
    bio: "Quisquam eius minus nemo quos voluptas dolores consequatur laudantium. Eaque dolorum et non eos. Occaecati vel soluta accusamus voluptatibus mollitia quis deserunt officia. Eligendi consequuntur aut ratione consequatur consequatur sint.\n \rConsequatur animi ut et reiciendis molestias occaecati quia. Ut debitis vero sit esse natus esse laboriosam velit quo. Sint sed facilis pariatur. Nulla cumque exercitationem error autem.\n \rIn officiis sunt ut iste natus et. Ullam non laudantium dignissimos eligendi id dolores aperiam corporis. Commodi possimus sed iusto recusandae deleniti ipsa nostrum. Nulla animi nisi est et temporibus modi quis ut quod.",
    day: "fri",
    scene: "Jotunheim",
    start: "20:00",
    end: "22:00",
  },
  {
    name: "Wilkinson - Boyle",
    members: ["Davon Treutel"],
    genre: "Jazz",
    logo: "https://placeimg.com/720/480/abstract?18901",
    bio: "Molestias et et tempora ea illum. Quidem molestiae iure iste. Aut quaerat dolor eum et itaque omnis tempora laudantium. Voluptas reiciendis consequatur.\n \rExcepturi quod fuga nihil reprehenderit velit dicta qui. Porro dolorem quo aliquid vitae modi. Nihil sed repellendus consequatur dolorem consectetur ut.\n \rAut et odit. Iste et nulla tempore aliquid. Nam quis dolore ullam expedita expedita molestias aperiam nesciunt. Nulla incidunt quo aut est aliquid.",
    day: "fri",
    scene: "Vanaheim",
    start: "16:00",
    end: "18:00",
  },
  {
    name: "Hilll - Weber",
    members: ["Ramiro Koelpin", "Anjali Cartwright", "Adriana Pfeffer"],
    genre: "Jazz",
    logo: "https://placeimg.com/720/480/nightlife?36972",
    bio: "Hic sit aliquid et. Pariatur qui labore debitis illum et qui ut. Non minima dicta qui nulla ipsum ducimus sint. Eum minus dolor reprehenderit et laboriosam magni quae. Molestiae dolorum dolore officia maiores et. Aliquid ad magnam quas ut unde quibusdam molestias.\n \rUllam dolore accusamus quia similique maxime ullam quibusdam maxime. Nisi error tenetur possimus earum debitis facilis qui odio nostrum. Voluptas maiores voluptatem totam voluptas recusandae. Explicabo quam ad provident eaque est distinctio qui voluptas. Illum sed adipisci autem eum sint doloremque non iusto. Neque est nesciunt hic et optio mollitia occaecati illum sit.\n \rUnde vitae porro eum quis qui ut autem libero. Et quis non. Enim vel quaerat illum temporibus labore assumenda. Et vel odio laborum iure quo quod occaecati a sequi. Libero voluptates illo sequi numquam corporis quam non.",
    day: "fri",
    scene: "Jotunheim",
    start: "04:00",
    end: "06:00",
  },
];

let filterGenre = ["Jazz"];

function filterAllGenres(bands, filterGenre) {
  const result = bands.filter((band) => {
    if (filterGenre.length !== 0) {
      return filterGenre.some((filt) => {
        //some = does the callback for any element in the array?
        return band.genre.includes(filt);
      });
    } else {
      return band;
    }
  });

  return result;
}
